### ISSUE TITLE
Aggiungere il topic itis-fermi-modena

### ISSUE THREAD

**Issue by Steffo99** [infopz/pzgram#5]
Ciao da un ex-studente del Fermi! 👋 

Ho visto che questo repository è correlato con l'[ITIS Fermi di Modena](https://www.fermi-mo.edu.it/pvw/app/MOIT0016/pvw_sito.php), e in particolare con l'indirizzo di **Informatica e Telecomunicazioni**.

Ho dato il via a un topic su GitHub per raccogliere tutti i repository relativi alle attività del Fermi: [**`itis-fermi-modena`**](https://github.com/topics/itis-fermi-modena)!

Sarebbe bello che tu aggiungessi questo repository al topic :)

## Come fare

Dalla pagina principale del progetto, clicca su **Manage topics**.

![](https://user-images.githubusercontent.com/1540885/82833182-9be97f80-9ebd-11ea-9bd1-3563e9e9b8e2.png)

Ti si aprirà una casella di testo dove potrai inserire i topic.  
Inizia a scrivere `itis-fermi-modena`, e GitHub ti suggerirà il topic completo.
Clicca sul suggerimento per aggiungerlo!
(Se il suggerimento non compare, scrivi `itis-fermi-modena` per intero e premi invio.)

![](https://user-images.githubusercontent.com/1540885/82833236-c3404c80-9ebd-11ea-9822-1a2d64ebee92.png)

Una volta aggiunto il topic, clicca su **Done** per salvare la modifica.

![](https://user-images.githubusercontent.com/1540885/82833248-ca675a80-9ebd-11ea-8d29-050363f56952.png)

**Finito!** Il tuo repository ora comparirà nel topic [`itis-fermi-modena`](https://github.com/topics/unimore-informatica)!  

Ricordati poi di chiudere questa issue quando avrai fatto :)

![](https://user-images.githubusercontent.com/1540885/82833418-38ac1d00-9ebe-11ea-9f1c-e95fc3976896.png)

_Se per qualche motivo non vuoi che il tuo progetto appaia nel topic, sentiti pure libero di chiudere questa issue senza rispondermi, non mi offendo :P_

**Comment by infopz** [comment]
Scusa se ci ho messo un po di tempo, ma e' da un bel po che non ci rimettevo le mani sopra
